function behavior_mod = Eye(behavior_mod, f_eye_timestamps, f_eye_area, ...
                            f_eye_xy_pos, ts_data_unit, ts_description, ts_comments, ...
                            xy_data_unit, xy_description, xy_comments)
    % function to add eye position and pupil tracking to processing module

    eye_timestamps = readNPY(f_eye_timestamps);
    eye_area = readNPY(f_eye_area);
    eye_xy_pos = readNPY(f_eye_xy_pos);

    pupil = types.core.TimeSeries('timestamps',  eye_timestamps(:, 2), ...
                 'data', eye_area', ...
                 'data_unit', ts_data_unit, ...
                 'description', ts_description, ...
                 'comments', ts_comments);

    eye_xy = types.core.TimeSeries('timestamps',eye_timestamps(:, 2), ...
                'data', eye_xy_pos, ...
                'data_unit', xy_data_unit, ...
                'description', xy_description, ...
                'comments', xy_comments);
    pupil_track = types.core.PupilTracking('timeseries', [pupil, eye_xy]);
    behavior_mod.nwbdatainterface.set(...
                    'PupilTracking', pupil_track);

end
