function behavior_mod = LickTimes(behavior_mod, f_lk_ts, data_unit, description)
    % add lick behavioral events to behavior processing module
    lick_timestamps = readNPY(f_lk_ts);
    lick_data = ones(length(lick_timestamps), 1);
    lick_ts = types.core.TimeSeries(...
                    'timestamps', lick_timestamps', ...
                    'data', lick_data, ...
                    'data_unit', data_unit, ...
                    'description', description);
    lick_behavior = types.core.BehavioralEvents('timeseries', lick_ts);
    behavior_mod.nwbdatainterface.set(...
                    'BehavioralEvents', lick_behavior);
end
