% GUI window to select parameters for PSTH plot
% Function gets input nwb file object and plot with given parameters
function psth_panel(nwb)
    % gui window
    f = figure('Position',[100 100 320 550]);
    f.Units = 'normalized';
    ha.Units = 'normalized';
    %%
    y_offset = 500;
    pad_height = 50;    
    header = uicontrol('Style', 'text', ...
                       'String', 'PSTH panel', ...
                       'Position', [120, y_offset-30, 80, 50], ...
                       'fontsize', 10);
    %%           
    valid_groups = [];
    groups_available = nwb.intervals_trials.vectordata.keys();
    for i = 1:length(groups_available)
        grp_data = nwb.intervals_trials.vectordata.get(...
                                           groups_available(i)).data.load;
        unq_count = unique(grp_data);
        if(unq_count <= 5)
            valid_groups = [groups_available(i), valid_groups];
        end
    end
    valid_groups = ['no-condition', valid_groups];
    %%                   
    groupBymenu = uicontrol('Style', 'text', ...
                            'String', 'Condition:', ...
                            'Position', ...
                            [30, y_offset-2*pad_height, 80, 50]);

    groupByTextBox = uicontrol('Style','popupmenu', ...
                             'Position', ...
                             [160, y_offset-2*pad_height+30, 120, 30], ...
                             'String', valid_groups);
    %%
    unitIdText = uicontrol('Style', 'text', ...
                           'String', 'Unit Id:', ...
                           'Position', ...
                           [30, y_offset - 3*pad_height, 80, 50]);

    unitIdTextBox = uicontrol('Style','edit',...
                              'String','1', ...
                              'Position', ...
                              [160, y_offset - 3*pad_height+30, 70, 30]);
    %%
    nbinsText = uicontrol('Style', 'text', ...
                          'String', 'Num. bins:', ...
                          'Position', ...
                          [30, y_offset - 4*pad_height, 80, 50]);

    nbinsTextBox = uicontrol('Style','edit', ...
                             'Position', ...
                             [160, y_offset - 4*pad_height+30, 70, 30], ...
                             'String', 30);
    %%
    beforeTimeText = uicontrol('Style', 'text', ...
                               'String', 'Before time:', ...
                               'Position', ...
                               [30, y_offset - 5*pad_height, 80, 50]);

    beforeTimeTextBox = uicontrol('Style','edit', ...
                          'Position', ...
                          [160, y_offset - 5*pad_height+30, 70, 30], ...
                          'String', -0.5);
    %%
    afterTimeText = uicontrol('Style', 'text', ...
                              'String', 'After time:', ...
                              'Position', ...
                              [30, y_offset - 6*pad_height, 80, 50]);

    afterTimeTextBox = uicontrol('Style','edit', ...
                             'Position', ...
                             [160, y_offset - 6*pad_height+30, 70, 30], ...
                             'String', 1.0);
    %%                        
    plotOptions = {'histogram', 'gaussian'};
    plotOptionmenu = uicontrol('Style', 'text', ...
                               'String', 'PSTH plot type:', ...
                               'Position', ...
                               [30, y_offset - 7*pad_height, 80, 50]);

    plotOptionTextBox = uicontrol('Style','popupmenu', ...
                         'Position', ...
                         [160, y_offset - 7*pad_height+25, 120, 30], ...
                         'String', plotOptions);
    %%
    stdText = uicontrol('Style', 'text', ...
                        'String', 'Standard dev.:', ...
                        'Position', [30, y_offset - 8*pad_height, 80, 50]);

    stdTextBox = uicontrol('Style','edit', ...
                           'Position', ...
                           [160, y_offset - 8*pad_height+30, 70, 30], ...
                           'String', 0.05);
    %%
    plot_button = uicontrol('Style','pushbutton',...
                            'String','Plot', ...
                            'Position',[100,20,100,30],...
                            'Callback',@plotbutton_Callback);

    f.Name = 'PSTH panel';
    movegui(f,'center');
    %% callback function to plot
    function plotbutton_Callback(source, eventdata)
        unit_id = str2num(get(unitIdTextBox, 'string'));
        val = groupByTextBox.Value;
        str = groupByTextBox.String;
        group_by = str{val};
        before_time = str2num(get(beforeTimeTextBox, 'string'));
        after_time = str2num(get(afterTimeTextBox, 'string'));
        n_bins = str2num(get(nbinsTextBox, 'string'));
        val = plotOptionTextBox.Value;
        str = plotOptionTextBox.String;
        plot_option = str{val};
        std = str2num(get(stdTextBox, 'string'));
        psth(nwb, unit_id, group_by, before_time, after_time, n_bins, ...
             plot_option, std);
    end
end
