% Function to read passive stimulus data and convert to corresponding
% TimeSeries objects
function [passive_beep_timeseries, passive_clicks_timseries, ...
          passive_left, passive_right, passive_white] = PassiveStim(...
                            file_prefix, data_units, descriptions)

    arguments
        file_prefix (1, :) string = ''
    end
    arguments (Repeating)
        data_units char
        descriptions char
    end
    %% add passive beeps
    fname_passive_beeps = strcat(file_prefix, 'passiveBeeps.times.npy');
    passive_beeps = readNPY(fname_passive_beeps);
    passive_beeps_data = uint8(ones(length(passive_beeps), 1));
    passive_beep_timeseries = types.core.TimeSeries(...
                                'timestamps', passive_beeps', ...
                                'data', passive_beeps_data, ...
                                'data_unit', cell2mat(data_units(1)), ...
                                'description', cell2mat(descriptions(1)));

    %% passive valve clicks
    fname_passive_clicks = strcat(file_prefix, 'passiveValveClick.times.npy');
    passive_clicks = readNPY(fname_passive_clicks);
    passive_clicks_data = uint8(ones(length(passive_clicks), 1));
    passive_clicks_timseries = types.core.TimeSeries(...
                                'timestamps', passive_clicks', ...
                                'data', passive_clicks_data, ...
                                'data_unit', cell2mat(data_units(2)), ...
                                'description', cell2mat(descriptions(2)));

    %% passive visual times
    fname_passivevisual_times = strcat(file_prefix, 'passiveVisual.times.npy');
    fname_passivevisual_left = strcat(file_prefix, 'passiveVisual.contrastLeft.npy');
    fname_passivevisual_right = strcat(file_prefix, 'passiveVisual.contrastRight.npy');
    passivevisual_times = readNPY(fname_passivevisual_times);
    passivevisual_left = readNPY(fname_passivevisual_left);
    passivevisual_right = readNPY(fname_passivevisual_right);

    passive_left = types.core.TimeSeries(...
                            'timestamps', passivevisual_times', ...
                            'data', passivevisual_left', ...
                            'data_unit', cell2mat(data_units(3)), ...
                            'description', cell2mat(descriptions(3)));

     passive_right = types.core.TimeSeries(...
                                'timestamps', passivevisual_times', ...
                                'data', passivevisual_right', ...
                                'data_unit', cell2mat(data_units(4)), ...
                                'description', cell2mat(descriptions(4)));

    %% passive valve clicks
    fname_passive_noise = strcat(file_prefix, 'passiveWhiteNoise.times.npy');
    passive_noise = readNPY(fname_passive_noise);
    passive_noise_data = uint8(ones(length(passive_noise), 1));
    passive_white = types.core.TimeSeries(...
                'timestamps', passive_noise', ...
                'data', passive_noise_data, ...
                'data_unit', cell2mat(data_units(5)), ...
                'description', cell2mat(descriptions(5)));

end
