% function to convert sparse noise stimuli data
function sparsenoise_timeseries = SparseNoise(file_prefix, data_unit, ...
                                              description, comments)
    arguments
        file_prefix (1, :) string = ''
        data_unit char = 'Unknown'
        description char = 'sparse noise as stimulus'
        comments char = 'No comments'
    end
    %%
    fname_sparsenoise_positions = strcat(file_prefix, ...
                                            'sparseNoise.positions.npy');
    fname_sparsenoise_times = strcat(file_prefix, ...
                                            'sparseNoise.times.npy');
    sparsenoise_positions = readNPY(fname_sparsenoise_positions);
    sparsenoise_times = readNPY(fname_sparsenoise_times);

    sparsenoise_timeseries = types.core.TimeSeries(...
                                'timestamps', sparsenoise_times', ...
                                'data', sparsenoise_positions', ...
                                'data_unit', data_unit, ...
                                'description', description, ...
                                'comments', comments);
end
